### ISSUE TITLE
Add sound ambiance/music

### ISSUE THREAD

**Issue by TheOptimisticFactory** [KoalaMoala/Feuer#11]
### Description

Currently there nothing to help the player get immersed into the game.
A music and ambiance sounds might spice things up 

(And make its related setting button actually useful)
### Goals
- [x] Find some sounds effects / ambiance sounds 
- [x] Find some music that could fit the theme

**Comment by JoeTheFkingFrypan** [comment]
### Update ###

Added fancy backgrounds for :

- the main screen (the one with choices) as per 93e1d7da56ea769ccbe6c6d6e1311ee18639913d
- the failure screen as per 904cf9b1de526aabef2b22f1c629f4c5c6bd2753
