### ISSUE TITLE
Implement scoring

### ISSUE THREAD

**Issue by TheOptimisticFactory** [KoalaMoala/Feuer#15]
### Goals
- [x] Ability to compute score based on user's actions
- [x] Ability to save user's score
- [x] Ability to display user's highscores

**Comment by TheOptimisticFactory** [comment]
### Update
- Progress has been made concerning the implementation of scoring as per 31f6ced63ca946194593467ed675ee4cc185258b and ecf4efc6999e0598dc2e35f3ae8a303146b1a600

**Comment by JoeTheFkingFrypan** [comment]
Update

- User's score for a particular level is now saved using SharedPreferences as per ecf4efc6999e0598dc2e35f3ae8a303146b1a600 and
